# Generated by Django 4.2.2 on 2023-06-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0002_remove_mymodel_field1_remove_mymodel_field2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Fouls",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="GA",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="GF",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Offside",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Possession",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Red",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots_Target",
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Yellow",
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
