# Generated by Django 4.2.2 on 2023-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0003_alter_mymodel_date_alter_mymodel_fouls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Fouls",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="GA",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="GF",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Offside",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Possession",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Red",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots_Target",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Yellow",
            field=models.IntegerField(null=True),
        ),
    ]
