# Generated by Django 4.2.2 on 2023-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0004_alter_mymodel_fouls_alter_mymodel_ga_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="Time",
        ),
    ]
