# Generated by Django 4.2.2 on 2023-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0005_remove_mymodel_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Date",
            field=models.CharField(default="DEFAULT", max_length=255),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Fouls",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Offside",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Possession",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Red",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots_Target",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Yellow",
            field=models.FloatField(null=True),
        ),
    ]
