# Generated by Django 4.2.2 on 2023-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0006_alter_mymodel_date_alter_mymodel_fouls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Date",
            field=models.DateField(default="DEFAULT"),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Fouls",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="GA",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="GF",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Offside",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Possession",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Red",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots_Target",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Yellow",
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=5),
        ),
    ]
