# Generated by Django 4.2.2 on 2023-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0007_alter_mymodel_date_alter_mymodel_fouls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Date",
            field=models.CharField(default="DEFAULT", max_length=255),
        ),
    ]
