# Generated by Django 4.2.2 on 2023-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0008_alter_mymodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Date",
            field=models.DateField(null=True),
        ),
    ]
