# Generated by Django 4.2.2 on 2023-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0009_alter_mymodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="Fouls",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Offside",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Possession",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Red",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Shots_Target",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="Yellow",
            field=models.IntegerField(default=-1),
        ),
    ]
