# Generated by Django 4.2.2 on 2023-06-21 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0010_alter_mymodel_fouls_alter_mymodel_offside_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="myModel",
            new_name="tableModel",
        ),
    ]
